
var SlayerMasters = {
	
	SPRIA : {
		id : 8462,
		combatLevel : 3,
		slayerLevel : 1		
	},
	TURAEL : {
		id : 8480,
		combatLevel : 3,
		slayerLevel : 1		
	},
	MAZCHNA : {
		id : 8481,
		combatLevel : 20,
		slayerLevel : 1		
	},
	ACHTRYN : {
		id : 8465,
		combatLevel : 20,
		slayerLevel : 1		
	},
	VANNAKA : {
		id : 1597,
		combatLevel : 40,
		slayerLevel : 1		
	},
	CHAELDAR : {
		id : 1598,
		combatLevel : 70,
		slayerLevel : 1		
	},
	SUMONA : {
		id : 7780,
		combatLevel : 85,
		slayerLevel : 35		
	},
	DURADEL : {
		id : 8466,
		combatLevel : 100,
		slayerLevel : 50	
	},
	LAPALOK : {
		id : 8467,
		combatLevel : 100,
		slayerLevel : 50	
	},
	KURADAL : {
		id : 9085,
		combatLevel : 110,
		slayerLevel : 75	
	},
	MORVAN : {
		id : 20112,
		combatLevel : 120,
		slayerLevel : 85	
	}
		
}

var Slayer = {
		
	SlayerTaskNames : {
		MIGHTY_BANSHEE : 37,
		MIGHTY_BANSEE : 37,
		BANSHEE : 15,
		BAT : 1,
		AVIANSIE : 1,
		TORMENTED_DEMON : 1,
		CHICKEN : 1,
		CHOMPY_BIRD: 1,
		DUCK: 1,
		BIRD: 1,
		BEAR : 1,
		CAVE_BUG : 7,
		CAVE_SLIME : 17,
		COW : 1,
		ZOMBIE_HAND : 5,
		SKELETAL_HAND : 5,
		CRAWLING_HAND : 5,
		DWARF : 1,
		LIZARD : 22,
		DESERT_LIZARD : 22,
		REVENANT : 1,
		GHOST : 1,
		GOBLIN : 1,
		ICEFIEND : 1,
		MINOTAUR : 1,
		MONKEY : 1,
		SCORPION : 1,
		SKELETON : 1,
		SPIDER : 1,
		WOLF : 1,
		ZOMBIE : 1,
		CATABLEPON : 1,
		CAVE_CRAWLER : 10,
		DOG : 1,
		FLESH_CRAWLER : 1,
		HOBGOBLIN : 1,
		KALPHITE : 1,
		ROCKSLUG : 20,
		ROCK_SLUG : 20,
		HOLE_IN_THE_WALL: 35,
		WALL_BEAST: 35,
		ABERRANT_SPECTRE : 60,
		ANKOU : 1,
		BASILISK : 40,
		BLOODVELD : 50,
		BRINE_RAT : 47,
		COCKATRICE : 25,
		CROCODILE : 1,
		CYCLOPS : 1,
		CYCLOPSE : 1,
		DUST_DEVIL : 65,
		EARTH_WARRIOR : 1,
		GHOUL : 1,
		GREEN_DRAGON : 1,
		GROTWORM : 1,
		HARPIE_BUG_SWARM : 33,
		HILL_GIANT : 1,
		ICE_GIANT : 1,
		ICE_WARRIOR : 1,
		INFERNAL_MAGE: 45,
		JELLY : 52,
		JUNGLE_HORROR : 1,
		LESSER_DEMON : 1,
		MOLANISK : 39,
		ELF_WARRIOR : 1,
		ELVES : 1,
		MOSS_GIANT : 1,
		OGRE : 1,
		OTHERWORLDLY_BEING : 1,
		PYREFIEND : 30,
		SHADE : 1,		
		SHADOW_WARRIOR : 1,
		NECHRYAEL : 80,
		TUROTH : 55,
		VAMPYRE : 1,
		WEREWOLF : 1,
		BLUE_DRAGON : 1,
		BRONZE_DRAGON: 1,
		CAVE_HORROR : 58,
		DAGANNOTH : 1,
		FEVER_SPIDER : 42,
		FIRE_GIANT : 1,
		FUNGAL_MAGE : 1,
		GARGOYLE : 75,
		GRIFOLAPINE : 88,
		GRIFOLAROO : 82,
		GRIFALOPINE : 88,
		GRIFALOROO: 82,
		JUNGLE_STRYKEWYRM : 73,
		KURASK : 70,
		FUNGI : 57,
		ZYGOMITE : 57,
		VYRELORD : 31,
		VYRELADY : 31,
		VYREWATCH : 31,
		WARPED_TORTOISE : 56,
		AQUANITES : 78,
		ABYSSAL_DEMON : 85,
		RORARI : 81,
		AIRUT : 92,
		EDIMMU : 90,
		GLACOR : 1,
		AQUANITE : 78,
		BLACK_DEMON : 1,
		DESERT_STRYKEWYRM : 77,
		GREATER_DEMON : 1,
		HELLHOUND : 1,
		IRON_DRAGON : 1,
		MUTATED_JADINKO_MALE : 91,
		MUTATED_JADINKO_GAURD : 86,
		MUTATED_JADINKO_BABY : 80,
		JADINKO : 1,
		RED_DRAGON : 1,
		SPIRITUAL_MAGE : 83,
		SPIRITUAL_WARRIOR : 68,
		TERROR_DOG : 40,
		BLACK_DRAGON : 1,
		CELESTIAL_DRAGON : 1,
		DARK_BEAST : 90,
		GANODERMIC : 95,
		GORAK : 1,
		ICE_STRYKEWYRM : 93,
		MITHRIL_DRAGON : 1,
		SKELETAL_WYVERN : 72,
		STEEL_DRAGON : 1,
		SUQAH : 1,
		WARPED_TERRORBIRD : 56,
		WATERFIEND : 1,
		LIVING_ROCK : 1,
		LAVA_STRYKEWYRM : 94,
		TZHAAR : 1		
	}
}